packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  "@nestjs/core": false
minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.0'
  - '@nestjs/core@12.1.0'
  - '@nestjs/platform-fastify@12.1.0'
  - '@nestjs/platform-express@12.1.0'
  - '@next/env@16.3.6'
  - '@next/swc-darwin-arm64@16.3.6'
  - '@next/swc-darwin-x64@16.3.6'
  - '@next/swc-linux-arm64-gnu@16.3.6'
  - '@next/swc-linux-arm64-musl@16.3.6'
  - '@next/swc-linux-x64-gnu@16.3.6'
  - '@next/swc-linux-x64-musl@16.3.6'
  - '@next/swc-win32-arm64-msvc@16.3.6'
  - '@next/swc-win32-x64-msvc@16.3.6'
  - next@16.3.6
